apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloweb
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
  labels:
    app: hello
spec:
  tls:
    - hosts:
        - app-ext.TODO-YOUR-DNS-ZONE.loodse.training
      secretName: loodse-dev-tls
  rules:
    - host: app-ext.TODO-YOUR-DNS-ZONE.loodse.training
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: helloweb
                port:
                  number: 80