apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-{{ .Values.color }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-{{ .Values.color }}-deployment
  template:
    metadata:
      labels:
        app: my-{{ .Values.color }}-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.2
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: my-{{ .Values.color }}-configmap
            items:
              - key: body
                path: index.html
